// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using portal.Data;

namespace portal.Migrations
{
    [DbContext(typeof(PortalContext))]
    partial class PortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("portal.Models.Language", b =>
                {
                    b.Property<int>("Lang_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lang_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lang_Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("portal.Models.Navigation", b =>
                {
                    b.Property<int>("Nav_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isGroup")
                        .HasColumnType("bit");

                    b.Property<int>("lang_id")
                        .HasColumnType("int");

                    b.Property<string>("nav_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nav_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nav_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nav_Id");

                    b.HasIndex("lang_id");

                    b.ToTable("Navigation");
                });

            modelBuilder.Entity("portal.Models.Navigation", b =>
                {
                    b.HasOne("portal.Models.Language", "Language")
                        .WithMany("navigations")
                        .HasForeignKey("lang_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("portal.Models.Language", b =>
                {
                    b.Navigation("navigations");
                });
#pragma warning restore 612, 618
        }
    }
}
